{% set name = "yaqd-scpi" %}
{% set version = "2021.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yaqd-scpi-{{ version }}.tar.gz
  sha256: ecf4cc5b6144fc61d63f291b19046ff30109adbae3c524b0b1b7973fb85f0021

build:
  number: 1
  noarch: python
  entry_points:
    - yaqd-scpi-sensor = yaqd_scpi._scpi_sensor:SCPISensor.main
    - yaqd-scpi-set-continuous = yaqd_scpi._scpi_set_continuous:SCPISetContinuous.main
    - yaqd-scpi-set-discrete = yaqd_scpi._scpi_set_discrete:SCPISetDiscrete.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit
  run:
    - python >={{ python_min }}
    - pyvisa
    - pyvisa-py
    - yaqd-core >=2020.10.0
    - flit

test:
  imports:
    - yaqd_scpi
  commands:
    - pip check
    - yaqd-scpi-sensor --help
    - yaqd-scpi-set-continuous --help
    - yaqd-scpi-set-discrete --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://yaq.fyi
  summary: yaq daemons for SCPI hardware
  dev_url: https://gitlab.com/yaq/yaqd-scpi
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BrandonMehlenbacher
    - untzag
    - ksunden
